apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhel-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhel-bootc
    app.kubernetes.io/part-of: rhel-bootc
  name: rhel-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhel-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhel-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:df83a53f356ac3921ec66f5f8df4719e28ca7544d8c234848beb946ec90c38e0
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
