apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhel-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhel-bootc
    app.kubernetes.io/part-of: rhel-bootc
  name: rhel-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhel-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhel-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:5f2a2fb00ab83beda1d8825236140e5915d24335848d5eb62cb669c043a82405
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
