apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhel-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhel-bootc
    app.kubernetes.io/part-of: rhel-bootc
  name: rhel-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhel-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhel-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:c0aea6a32d93bf70d1f02f4f6eaf9a5a58952a4ae10cdd3058698f59b3cc5d30
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
