apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhel-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhel-bootc
    app.kubernetes.io/part-of: rhel-bootc
  name: rhel-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhel-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhel-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:f82f9810999b40e8a33646a6d35d81d6a17705a815a927749eb91f933eddb8f7
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
