apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhel-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:0849a694c50056682498aaae905cec0b37a837551bad64d6fcd815ac67f372d0
        name: container-image
        resources: {}
status: {}
