apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhel-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:37bdda91f4f53e4c2b0055b648d5434378ef2f009245a571a0fc520f8474256d
        name: container-image
        resources: {}
status: {}
