apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhel-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:36ebf3b1bea7fad66a73ac785f44dd3c60e5107f302ce634f28407ea299e8079
        name: container-image
        resources: {}
status: {}
