apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhel-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:ece80eb17d2b8a2d0fc5aec279e567fd8f463e4240c3a5a5191e765e9b17cbb4
        name: container-image
        resources: {}
status: {}
