apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhel-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/rhel-bootc/rhel-bootc@sha256:164bcf13b0d149ff7dc3c7a0581762ba4ed3c0daefd83237483df9598967b1cc
        name: container-image
        resources: {}
status: {}
